### ISSUE TITLE
Compilation fails on stable channel due to use of `#![feature]`

### ISSUE THREAD

**Issue by sarahec** [lemonrock/file-descriptors#2]
When attempting to compile using Rust 1.53:
```sh
error[E0554]: `#![feature]` may not be used on the stable release channel
  --> /home/sec/.cargo/registry/src/github.com-1ecc6299db9ec823/file-descriptors-0.9.1/src/lib.rs:10:1
   |
10 | #![feature(core_intrinsics)]
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0554]: `#![feature]` may not be used on the stable release channel
  --> /home/sec/.cargo/registry/src/github.com-1ecc6299db9ec823/file-descriptors-0.9.1/src/lib.rs:11:1
   |
11 | #![feature(read_initializer)]
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

`read_initializer` almost has an implementation, but is delayed due to performance regressions.  

What would it take to make this work without the custom features?

**Comment by raphaelcohn** [comment]
Please do not use this project, but use the `linux-support` crate instead.

Note that it is impossible to write performant Rust code today without relying on nightly features, and probably will do for a long time to come.

**Comment by sarahec** [comment]
Thank you. Closing.
